### PR TITLE
Fix find command behaviour

### LINKED ISSUE #172: Find does not show the tab in which the person found is in
After submitting a find command, the tab view refreshes back to the first module tab, causing the user to manually click on tabs to find the person.

Possible solutions: 
- Refresh back to view all after a find command
- If refreshing in tab view, then possibly refresh to the first module and tutorial tab in which a person is found

### PR DESCRIPTION
**Pull request by jordon0802**
Find command in tab view will now switch to the tab of the persons first module tutorial group
Closes #172

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/FindCommand.java [hunk 1]
```diff
@@ -38,6 +40,13 @@ public FindCommand(FieldContainsKeywordsPredicate predicate) {
     public CommandResult execute(Model model) {
         requireNonNull(model);
         model.updateFilteredPersonList(predicate);
+        if (!model.getFilteredPersonList().isEmpty()) {
+            Person firstPerson = model.getFilteredPersonList().get(0);
+            ModTutGroup firstModTutGroup = firstPerson.getModTutGroups().iterator().next();
+            String moduleName = firstModTutGroup.getModule().getName();
```
Comment (potatodudedude) [inline src/main/java/seedu/address/logic/commands/FindCommand.java:46]: It seems you're using person.getModTutGroups().iterator().next().getModule().getName() or person.getModTutGroups().iterator().next().getTutorial().getName() a lot for updating the view tabs after a command. 

You could try extracting out the command to something like getFirstModuleName() and getFirstModuleTutorialName() under Person and shortening ModTutGroup.getModule().getName() to just ModtutGroup.getModuleName() etc.

**Comment by potatodudedude** [comment]
Merging cause of time constraint
