### PR TITLE
Fix add command message usage text

### LINKED ISSUE #181: Add command message not displaying correctly
### Showing
Invalid command format! 
add: Adds a person to ConnectS.
Parameters: n/NAME t/TELEGRAM HANDLE e/EMAIL [m/MOD-TUT GROUP]... [tag/TAG]...
Example: add n/John Doe t/@johndoe123 e/johnd@example.com m/CS2103T-T21 m/CS2109S-T05[tag/TAG]... tag/need more help tag/bad at programming
### Should probably look like
Invalid command format! 
add: Adds a person to ConnectS.
Parameters: n/NAME t/TELEGRAM HANDLE e/EMAIL [m/MOD-TUT GROUP]... [tag/TAG]...
Example: add n/John Doe t/@johndoe123 e/johnd@example.com m/CS2103T-T21 m/CS2109S-T05 tag/need more help tag/bad at programming

### PR DESCRIPTION
**Pull request by jordon0802**
Closes #181

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 1]
```diff
@@ -25,17 +25,16 @@ public class AddCommand extends Command {
...
             + PREFIX_NAME + "John Doe "
             + PREFIX_TELEGRAM + "@johndoe123 "
             + PREFIX_EMAIL + "johnd@example.com "
             + PREFIX_MOD + "CS2103T-T21 "
-            + PREFIX_MOD + "CS2109S-T05"
-            + "[" + PREFIX_TAG + "TAG]...\n"
+            + PREFIX_MOD + "CS2109S-T05 "
             + PREFIX_TAG + "need more help "
-            + PREFIX_TAG + "bad at programming";;
+            + PREFIX_TAG + "bad at programming";
```
Comment (potatodudedude) [inline src/main/java/seedu/address/logic/commands/AddCommand.java:37]: tags currently only allow one term without spaces, can update the message to a single word like "struggling" or "exchangestudent"

**Comment by potatodudedude** [comment]
LGTM
